import fluentTokens from '../../../../tokens/fluent.json';
import materialTokens from '../../../../tokens/material.json';

export type Variant = 'hover' | 'focus' | 'active' | 'dark';
export type Family = 'f' | 'm' | 'ui';
export type TokenMap = Record<string, string>;
export type TokenGroup = Record<string, TokenMap>;

export type ParsedClass = {
  raw: string;
  variants: Variant[];
  family: Family;
  utility: string;
  value: string | null;
};

export type Declaration = {
  property: string;
  value: string;
};

export type RuleMatch = {
  rawClassName: string;
  variants: Variant[];
  declarations: Declaration[];
};

const DEFAULT_STYLESHEET_HEADER = '/* motif.css: generated by motif */';
const DEFAULT_KEYFRAMES = [
  '@keyframes motif-spin {\n  to {\n    transform: rotate(360deg);\n  }\n}',
  '@keyframes motif-shimmer {\n  0% {\n    background-position: 200% 0;\n  }\n  100% {\n    background-position: -200% 0;\n  }\n}',
];
const CLASS_BOUNDARY = /[\s"'`<>=\{\}\(\)\[\],;]/;
const CLASS_CHAR = /^[A-Za-z0-9:/_.-]+$/;

const registry = {
  fluent: fluentTokens as TokenGroup,
  material: materialTokens as TokenGroup,
};

export function extractClassNames(content: string): Set<string> {
  const result = new Set<string>();
  for (const candidate of content.split(CLASS_BOUNDARY)) {
    const normalized = normalizeCandidate(candidate);
    if (normalized) {
      result.add(normalized);
    }
  }
  return result;
}

function normalizeCandidate(candidate: string): string | null {
  let start = 0;
  let end = candidate.length;

  while (start < end && !isClassChar(candidate[start]!)) {
    start += 1;
  }
  while (end > start && !isClassChar(candidate[end - 1]!)) {
    end -= 1;
  }

  const trimmed = candidate.slice(start, end);
  if (!trimmed || !CLASS_CHAR.test(trimmed)) {
    return null;
  }

  const utility = trimmed.split(':').at(-1) ?? trimmed;
  if (utility.startsWith('f-') || utility.startsWith('m-') || utility.startsWith('ui-')) {
    return trimmed;
  }
  return null;
}

function isClassChar(value: string): boolean {
  return /[A-Za-z0-9:/_.-]/.test(value);
}

export function parseClassName(input: string): ParsedClass | null {
  if (!input) {
    return null;
  }

  const segments = input.split(':');
  const base = segments.pop();
  if (!base) {
    return null;
  }

  const variants = segments.every(isVariant) ? (segments as Variant[]) : null;
  if (!variants) {
    return null;
  }

  const family = base.startsWith('f-')
    ? 'f'
    : base.startsWith('m-')
      ? 'm'
      : base.startsWith('ui-')
        ? 'ui'
        : null;
  if (!family) {
    return null;
  }

  const body = family === 'ui' ? base.slice(3) : base.slice(2);
  if (!body) {
    return null;
  }

  const [utility, value] = splitUtility(body);
  if (!utility) {
    return null;
  }

  return {
    raw: input,
    variants,
    family,
    utility,
    value,
  };
}

function isVariant(value: string): value is Variant {
  return value === 'hover' || value === 'focus' || value === 'active' || value === 'dark';
}

function splitUtility(body: string): [string, string | null] {
  const dash = body.indexOf('-');
  if (dash === -1) {
    return [body, null];
  }
  return [body.slice(0, dash), body.slice(dash + 1)];
}

export function resolveUniversal(parsed: ParsedClass): Declaration[] | null {
  switch (`${parsed.utility}:${parsed.value ?? ''}`) {
    case 'control:sm':
      return control('2.25rem', '0.625rem 0.85rem', '0.875rem');
    case 'control:md':
      return control('2.75rem', '0.78rem 0.95rem', '0.95rem');
    case 'control:lg':
      return control('3.25rem', '0.95rem 1.2rem', '1rem');
    case 'pad:sm':
      return [decl('padding', '0.75rem')];
    case 'pad:md':
      return [decl('padding', '1rem')];
    case 'pad:lg':
      return [decl('padding', '1.25rem')];
    case 'radius:sm':
      return [decl('border-radius', '6px')];
    case 'radius:md':
      return [decl('border-radius', '10px')];
    case 'radius:lg':
      return [decl('border-radius', '14px')];
    case 'radius:pill':
      return [decl('border-radius', '999px')];
    case 'text:sm':
      return text('0.875rem', '1.4');
    case 'text:md':
      return text('1rem', '1.5');
    case 'text:lg':
      return text('1.125rem', '1.55');
    default:
      return null;
  }
}

export function renderStylesheet(rules: RuleMatch[]): string {
  const blocks = [DEFAULT_STYLESHEET_HEADER, ...DEFAULT_KEYFRAMES, ...rules.map(renderRule)];
  return `${blocks.join('\n\n')}\n`;
}

function renderRule(rule: RuleMatch): string {
  let pseudoSuffix = '';
  let isDark = false;
  for (const variant of rule.variants) {
    if (variant === 'dark') {
      isDark = true;
      continue;
    }
    pseudoSuffix += `:${variant}`;
  }

  const selector = `.${escapeClassName(rule.rawClassName)}`;
  const body = rule.declarations
    .map((declaration) => `  ${declaration.property}: ${declaration.value};`)
    .join('\n');
  const block = `${selector}${pseudoSuffix} {\n${body}\n}`;
  return isDark ? `@media (prefers-color-scheme: dark) {\n${indent(block, 2)}\n}` : block;
}

function escapeClassName(input: string): string {
  return input.replaceAll(':', '\\:').replaceAll('/', '\\/').replaceAll('.', '\\.');
}

function indent(input: string, spaces: number): string {
  const prefix = ' '.repeat(spaces);
  return input
    .split('\n')
    .map((line) => `${prefix}${line}`)
    .join('\n');
}

export function decl(property: string, value: string): Declaration {
  return { property, value };
}

export function tokenDecl(property: string, value: string): Declaration {
  return { property, value };
}

export function actionLayout(): Declaration[] {
  return [
    decl('display', 'inline-flex'),
    decl('align-items', 'center'),
    decl('justify-content', 'center'),
    decl('min-height', '2.5rem'),
    decl('line-height', '1'),
  ];
}

export function control(minHeight: string, padding: string, fontSize: string): Declaration[] {
  return [
    decl('min-height', minHeight),
    decl('padding', padding),
    decl('font-size', fontSize),
  ];
}

export function text(fontSize: string, lineHeight: string): Declaration[] {
  return [decl('font-size', fontSize), decl('line-height', lineHeight)];
}

export function withTransition(
  declarations: Declaration[],
  property: string,
  duration: string,
  easing: string,
): Declaration[] {
  return [
    ...declarations,
    tokenDecl('transition-property', property),
    tokenDecl('transition-duration', duration),
    tokenDecl('transition-timing-function', easing),
  ];
}

export function fluentTypography(sizeKey: string, weightKey: string, color?: string): Declaration[] {
  return typography(registry.fluent.typography, sizeKey, weightKey, color);
}

export function materialTypography(sizeKey: string, weightKey: string, color?: string): Declaration[] {
  return typography(registry.material.typography, sizeKey, weightKey, color);
}

function typography(tokens: TokenMap, sizeKey: string, weightKey: string, color?: string): Declaration[] {
  const declarations = [
    tokenDecl('font-family', tokens['font-family']),
    tokenDecl('font-size', tokens[sizeKey]),
    tokenDecl('font-weight', tokens[weightKey]),
    tokenDecl('line-height', tokens['line-height']),
    tokenDecl('letter-spacing', tokens.tracking),
  ];
  if (color) {
    declarations.push(tokenDecl('color', color));
  }
  return declarations;
}

export function fluent(group: string, key: string): string {
  return getToken(registry.fluent, group, key);
}

export function material(group: string, key: string): string {
  return getToken(registry.material, group, key);
}

function getToken(source: TokenGroup, group: string, key: string): string {
  const groupValues = source[group];
  if (!groupValues || !(key in groupValues)) {
    throw new Error(`missing motif token ${group}.${key}`);
  }
  return groupValues[key]!;
}
