import test from 'node:test';
import assert from 'node:assert/strict';
import { compileSources } from '../../src/core.js';

// Smoke tests pin the smallest cross-section of parser/render behavior so shared helpers
// can be refactored without losing coverage for variants, dedupe, and universal utilities.
test('compileSources renders preset rules and variants into a stylesheet', () => {
  const result = compileSources([
    {
      path: '/demo/App.tsx',
      content: `
        <main class="f-surface m-surface-container ui-pad-lg">
          <button class="hover:f-bg-hover-primary focus:f-ring dark:m-elevation-1 ui-control-lg ui-radius-pill ui-gap-lg"></button>
        </main>
      `,
    },
  ]);

  assert.match(result.stylesheet, /\/\* motif\.css: generated by motif \*\//);
  assert.match(result.stylesheet, /\.f-surface \{/);
  assert.match(result.stylesheet, /background-image:/);
  assert.match(result.stylesheet, /\.hover\\:f-bg-hover-primary:hover \{/);
  assert.match(result.stylesheet, /@media \(prefers-color-scheme: dark\)/);
  assert.match(result.stylesheet, /\.dark\\:m-elevation-1 \{/);
  assert.match(result.stylesheet, /\.ui-control-lg \{/);
  assert.match(result.stylesheet, /\.ui-gap-lg \{/);
  assert.match(result.stylesheet, /gap: 1rem;/);
  assert.match(result.stylesheet, /border-radius: 999px;/);
});

test('compileSources ignores unknown tokens and deduplicates repeated classes', () => {
  const result = compileSources([
    {
      path: '/demo/one.tsx',
      content: '<div class="f-title f-title unknown-token"></div>',
    },
    {
      path: '/demo/two.tsx',
      content: '<div class="f-title"></div>',
    },
  ]);

  const titleMatches = result.stylesheet.match(/\.f-title \{/g) ?? [];
  assert.equal(titleMatches.length, 1);
  assert.doesNotMatch(result.stylesheet, /unknown-token/);
});

test('compileSources safely trims repeated punctuation around class candidates', () => {
  const repeatedCommas = ','.repeat(4096);
  const result = compileSources([
    {
      path: '/demo/Punctuation.tsx',
      content: `<div class="${repeatedCommas}f-title${repeatedCommas}"></div>`,
    },
  ]);

  assert.match(result.stylesheet, /\.f-title \{/);
});

test('compileSources renders first form control components for both presets', () => {
  const result = compileSources([
    {
      path: '/demo/Form.tsx',
      content: `
        <input type="checkbox" class="f-checkbox" />
        <input type="radio" class="m-radio" />
        <button class="m-switch"></button>
      `,
    },
  ]);

  assert.match(result.stylesheet, /\.f-checkbox \{/);
  assert.match(result.stylesheet, /\.m-radio \{/);
  assert.match(result.stylesheet, /\.m-switch \{/);
  assert.match(result.stylesheet, /inline-size: 2.5rem;/);
});

test('compileSources renders second batch component semantics', () => {
  const result = compileSources([
    {
      path: '/demo/Workspace.tsx',
      content: `
        <textarea class="f-textarea"></textarea>
        <button class="f-action-outlined"></button>
        <select class="m-select"></select>
        <button class="m-tab"></button>
        <section class="f-dialog"></section>
        <div class="m-list-item"></div>
        <button class="f-menu-item"></button>
      `,
    },
  ]);

  assert.match(result.stylesheet, /\.f-textarea \{/);
  assert.match(result.stylesheet, /\.f-action-outlined \{/);
  assert.match(result.stylesheet, /background-color: transparent;/);
  assert.match(result.stylesheet, /\.m-select \{/);
  assert.match(result.stylesheet, /\.m-tab \{/);
  assert.match(result.stylesheet, /\.f-dialog \{/);
  assert.match(result.stylesheet, /\.m-list-item \{/);
  assert.match(result.stylesheet, /\.f-menu-item \{/);
  assert.match(result.stylesheet, /max-width: 32rem;/);
  assert.match(result.stylesheet, /background-blend-mode: screen;/);
});

test('compileSources renders third batch navigation and feedback semantics', () => {
  const result = compileSources([
    {
      path: '/demo/Nav.tsx',
      content: `
        <button class="f-icon-button"></button>
        <a class="m-nav-item"></a>
        <span class="m-badge"></span>
        <div class="f-tooltip"></div>
        <section class="m-banner"></section>
      `,
    },
  ]);

  assert.match(result.stylesheet, /\.f-icon-button \{/);
  assert.match(result.stylesheet, /\.m-nav-item \{/);
  assert.match(result.stylesheet, /\.m-badge \{/);
  assert.match(result.stylesheet, /\.f-tooltip \{/);
  assert.match(result.stylesheet, /\.m-banner \{/);
  assert.match(result.stylesheet, /border: 1px solid #b6c3d6;/);
});




