import fluentTokens from '../../../tokens/fluent.json';
import materialTokens from '../../../tokens/material.json';
import type { MotifCompileAdapter, MotifCompileResult, MotifSourceFile } from './types.js';

type Variant = 'hover' | 'focus' | 'active' | 'dark';
type Family = 'f' | 'm';
type TokenMap = Record<string, string>;
type TokenGroup = Record<string, TokenMap>;

type ParsedClass = {
  raw: string;
  variants: Variant[];
  family: Family;
  utility: string;
  value: string | null;
};

type Declaration = {
  property: string;
  value: string;
};

type RuleMatch = {
  rawClassName: string;
  variants: Variant[];
  declarations: Declaration[];
};

const DEFAULT_STYLESHEET_HEADER = '/* motif.css: generated by motif */';
const CLASS_BOUNDARY = /[\s"'`<>=\{\}\(\)\[\],;]/;
const CLASS_CHAR = /^[A-Za-z0-9:/_.-]+$/;

const registry = {
  fluent: fluentTokens as TokenGroup,
  material: materialTokens as TokenGroup,
};

export function createTsCoreAdapter(): MotifCompileAdapter {
  return {
    compileSources(sources) {
      return compileSources(sources);
    },
  };
}

export function compileSources(sources: MotifSourceFile[]): MotifCompileResult {
  const classNames = new Set<string>();
  for (const source of sources) {
    for (const className of extractClassNames(source.content)) {
      classNames.add(className);
    }
  }

  const rules = Array.from(classNames)
    .sort((left, right) => left.localeCompare(right))
    .map(parseClassName)
    .filter((parsed): parsed is ParsedClass => parsed !== null)
    .map(resolveRule)
    .filter((rule): rule is RuleMatch => rule !== null);

  return {
    stylesheet: renderStylesheet(rules),
  };
}

function extractClassNames(content: string): Set<string> {
  const result = new Set<string>();
  for (const candidate of content.split(CLASS_BOUNDARY)) {
    const normalized = normalizeCandidate(candidate);
    if (normalized) {
      result.add(normalized);
    }
  }
  return result;
}

function normalizeCandidate(candidate: string): string | null {
  const trimmed = candidate.replace(/^[^A-Za-z0-9:/_.-]+|[^A-Za-z0-9:/_.-]+$/g, '');
  if (!trimmed || !CLASS_CHAR.test(trimmed)) {
    return null;
  }

  const utility = trimmed.split(':').at(-1) ?? trimmed;
  if (utility.startsWith('f-') || utility.startsWith('m-')) {
    return trimmed;
  }
  return null;
}

function parseClassName(input: string): ParsedClass | null {
  if (!input) {
    return null;
  }

  const segments = input.split(':');
  const base = segments.pop();
  if (!base) {
    return null;
  }

  const variants = segments.every(isVariant) ? (segments as Variant[]) : null;
  if (!variants) {
    return null;
  }

  const family = base.startsWith('f-') ? 'f' : base.startsWith('m-') ? 'm' : null;
  if (!family) {
    return null;
  }

  const body = base.slice(2);
  if (!body) {
    return null;
  }

  const [utility, value] = splitUtility(body);
  if (!utility) {
    return null;
  }

  return {
    raw: input,
    variants,
    family,
    utility,
    value,
  };
}

function isVariant(value: string): value is Variant {
  return value === 'hover' || value === 'focus' || value === 'active' || value === 'dark';
}

function splitUtility(body: string): [string, string | null] {
  const dash = body.indexOf('-');
  if (dash === -1) {
    return [body, null];
  }
  return [body.slice(0, dash), body.slice(dash + 1)];
}

function resolveRule(parsed: ParsedClass): RuleMatch | null {
  const declarations = parsed.family === 'f' ? resolveFluent(parsed) : resolveMaterial(parsed);
  if (!declarations) {
    return null;
  }
  return {
    rawClassName: parsed.raw,
    variants: parsed.variants,
    declarations,
  };
}

function resolveFluent(parsed: ParsedClass): Declaration[] | null {
  switch (`${parsed.utility}:${parsed.value ?? ''}`) {
    case 'stack:':
      return [decl('display', 'flex'), decl('flex-direction', 'column'), tokenDecl('gap', fluent('space', 'md'))];
    case 'ring:':
      return withTransition(
        [
          tokenDecl('outline-width', fluent('outline', 'focus-width')),
          decl('outline-style', 'solid'),
          tokenDecl('outline-color', fluent('color', 'primary')),
          tokenDecl('outline-offset', fluent('space', 'focus-offset')),
        ],
        fluent('effect', 'transition'),
        fluent('motion', 'duration'),
        fluent('motion', 'easing'),
      );
    case 'bg:primary':
      return [
        tokenDecl('background-color', fluent('color', 'primary')),
        tokenDecl('color', fluent('color', 'action-foreground')),
      ];
    case 'bg:hover-primary':
      return [
        tokenDecl('background-color', fluent('color', 'hover-primary')),
        tokenDecl('color', fluent('color', 'action-foreground')),
      ];
    case 'bg:hover-subtle':
      return [tokenDecl('background-color', fluent('color', 'hover-subtle'))];
    case 'text:primary':
      return [tokenDecl('color', fluent('color', 'primary'))];
    case 'text:muted':
      return [tokenDecl('color', fluent('color', 'muted'))];
    case 'surface:':
      return withTransition(
        [
          tokenDecl('background-color', fluent('color', 'surface')),
          tokenDecl('background-image', fluent('effect', 'surface-tint')),
          decl('background-blend-mode', 'screen'),
          tokenDecl('color', fluent('color', 'text')),
          tokenDecl('border-radius', fluent('radius', 'md')),
          tokenDecl('padding', fluent('space', 'surface-pad')),
          tokenDecl('border-width', fluent('border', 'subtle-width')),
          decl('border-style', 'solid'),
          tokenDecl('border-color', fluent('color', 'border')),
          tokenDecl('box-shadow', fluent('shadow', 'surface')),
          decl('backdrop-filter', 'blur(18px) saturate(1.15)'),
        ],
        fluent('effect', 'transition'),
        fluent('motion', 'duration'),
        fluent('motion', 'easing'),
      );
    case 'surface:alt':
      return withTransition(
        [
          tokenDecl('background-color', fluent('color', 'surface-alt')),
          tokenDecl('background-image', fluent('effect', 'surface-alt-tint')),
          decl('background-blend-mode', 'screen'),
          tokenDecl('color', fluent('color', 'text')),
          tokenDecl('border-radius', fluent('radius', 'sm')),
          tokenDecl('padding', fluent('space', 'surface-pad-sm')),
          tokenDecl('border-width', fluent('border', 'subtle-width')),
          decl('border-style', 'solid'),
          tokenDecl('border-color', fluent('color', 'border-strong')),
          tokenDecl('box-shadow', fluent('shadow', 'surface-alt')),
          decl('backdrop-filter', 'blur(28px) saturate(1.25)'),
        ],
        fluent('effect', 'transition'),
        fluent('motion', 'duration'),
        fluent('motion', 'easing'),
      );
    case 'panel:':
      return withTransition(
        [
          tokenDecl('background-color', fluent('color', 'panel')),
          tokenDecl('background-image', fluent('effect', 'panel-tint')),
          decl('background-blend-mode', 'screen'),
          tokenDecl('color', fluent('color', 'text')),
          tokenDecl('border', fluent('border', 'panel')),
          tokenDecl('border-radius', fluent('radius', 'lg')),
          tokenDecl('padding', fluent('space', 'panel-pad')),
          tokenDecl('box-shadow', fluent('shadow', 'panel')),
          decl('backdrop-filter', 'blur(24px) saturate(1.2)'),
        ],
        fluent('effect', 'interactive-transition'),
        fluent('motion', 'duration'),
        fluent('motion', 'easing'),
      );
    case 'shadow:press':
      return [tokenDecl('box-shadow', fluent('shadow', 'press'))];
    case 'title:':
      return fluentTypography('title-size', 'title-weight', fluent('color', 'text'));
    case 'body:':
      return fluentTypography('body-size', 'body-weight', fluent('color', 'text'));
    case 'label:':
      return fluentTypography('label-size', 'label-weight', fluent('color', 'muted'));
    case 'border:focus':
      return [tokenDecl('border', fluent('color', 'border-focus'))];
    case 'divider:':
      return [decl('display', 'block'), tokenDecl('border-bottom', fluent('border', 'divider'))];
    case 'field:':
      return withTransition(
        [
          ...fluentTypography('body-size', 'body-weight'),
          decl('min-height', '2.75rem'),
          tokenDecl('color', fluent('color', 'text')),
          tokenDecl('caret-color', fluent('color', 'primary')),
          tokenDecl('background-color', fluent('color', 'field')),
          tokenDecl('background-image', fluent('effect', 'field-tint')),
          tokenDecl('border', fluent('border', 'field')),
          tokenDecl('border-radius', fluent('radius', 'sm')),
          tokenDecl('padding', fluent('space', 'field-pad')),
          tokenDecl('box-shadow', fluent('shadow', 'field')),
          decl('backdrop-filter', 'blur(14px) saturate(1.05)'),
        ],
        fluent('effect', 'interactive-transition'),
        fluent('motion', 'duration'),
        fluent('motion', 'easing'),
      );
    case 'action:primary':
      return withTransition(
        [
          ...actionLayout(),
          ...fluentTypography('label-size', 'label-weight'),
          tokenDecl('color', fluent('color', 'action-foreground')),
          tokenDecl('background-color', fluent('color', 'primary')),
          tokenDecl('border', fluent('border', 'action-primary')),
          tokenDecl('border-radius', fluent('radius', 'md')),
          tokenDecl('padding', fluent('space', 'action-pad')),
          tokenDecl('box-shadow', fluent('shadow', 'action')),
        ],
        fluent('effect', 'interactive-transition'),
        fluent('motion', 'duration'),
        fluent('motion', 'easing'),
      );
    case 'action:subtle':
      return withTransition(
        [
          ...actionLayout(),
          ...fluentTypography('label-size', 'label-weight'),
          tokenDecl('color', fluent('color', 'primary')),
          tokenDecl('background-color', fluent('color', 'action-subtle')),
          tokenDecl('border', fluent('border', 'action-subtle')),
          tokenDecl('border-radius', fluent('radius', 'md')),
          tokenDecl('padding', fluent('space', 'action-pad')),
          tokenDecl('box-shadow', fluent('shadow', 'action-subtle')),
          decl('backdrop-filter', 'blur(18px) saturate(1.08)'),
        ],
        fluent('effect', 'interactive-transition'),
        fluent('motion', 'duration'),
        fluent('motion', 'easing'),
      );
    default:
      return null;
  }
}

function resolveMaterial(parsed: ParsedClass): Declaration[] | null {
  switch (`${parsed.utility}:${parsed.value ?? ''}`) {
    case 'surface:':
      return withTransition(
        [
          tokenDecl('background-color', material('color', 'surface')),
          tokenDecl('background-image', material('effect', 'surface-tint')),
          tokenDecl('color', material('color', 'on-surface')),
          tokenDecl('border-radius', material('radius', 'lg')),
          decl('padding', '1.25rem'),
          tokenDecl('box-shadow', material('shadow', 'surface')),
        ],
        material('effect', 'transition'),
        material('motion', 'duration'),
        material('motion', 'easing'),
      );
    case 'surface:container':
      return withTransition(
        [
          tokenDecl('background-color', material('color', 'surface-container')),
          tokenDecl('background-image', material('effect', 'container-tint')),
          tokenDecl('color', material('color', 'on-surface')),
          tokenDecl('border', material('border', 'surface-container')),
          tokenDecl('border-radius', material('radius', 'lg')),
          decl('padding', '1rem'),
          tokenDecl('box-shadow', material('shadow', 'container-high')),
        ],
        material('effect', 'state-transition'),
        material('motion', 'duration'),
        material('motion', 'easing'),
      );
    case 'surface:variant':
      return withTransition(
        [
          tokenDecl('background-color', material('color', 'surface-variant')),
          tokenDecl('background-image', material('effect', 'variant-tint')),
          tokenDecl('color', material('color', 'on-surface')),
          tokenDecl('border-radius', material('radius', 'lg')),
          decl('padding', '1rem'),
          tokenDecl('box-shadow', material('shadow', 'container')),
        ],
        material('effect', 'transition'),
        material('motion', 'duration'),
        material('motion', 'easing'),
      );
    case 'bg:primary':
      return withTransition(
        [
          tokenDecl('background-color', material('color', 'primary')),
          tokenDecl('color', material('color', 'on-primary')),
          tokenDecl('border-radius', material('radius', 'pill')),
        ],
        material('effect', 'state-transition'),
        material('motion', 'duration'),
        material('motion', 'easing'),
      );
    case 'bg:hover-primary':
      return [tokenDecl('background-color', material('color', 'hover-primary'))];
    case 'bg:hover-container':
      return [tokenDecl('background-color', material('color', 'hover-container'))];
    case 'bg:hover-surface':
      return [tokenDecl('background-color', material('color', 'hover-surface'))];
    case 'bg:primary-container':
      return withTransition(
        [
          tokenDecl('background-color', material('color', 'primary-container')),
          tokenDecl('color', material('color', 'on-primary-container')),
          tokenDecl('border-radius', material('radius', 'lg')),
          tokenDecl('box-shadow', material('shadow', 'container')),
        ],
        material('effect', 'state-transition'),
        material('motion', 'duration'),
        material('motion', 'easing'),
      );
    case 'text:primary':
      return [tokenDecl('color', material('color', 'primary'))];
    case 'text:on-primary':
      return [tokenDecl('color', material('color', 'on-primary'))];
    case 'text:muted':
      return [tokenDecl('color', material('color', 'muted'))];
    case 'ring:':
      return withTransition(
        [
          decl('outline-width', '2px'),
          decl('outline-style', 'solid'),
          tokenDecl('outline-color', material('color', 'primary')),
          decl('outline-offset', '2px'),
          decl('box-shadow', '0 0 0 4px rgba(26, 115, 232, 0.16)'),
        ],
        material('effect', 'state-transition'),
        material('motion', 'duration'),
        material('motion', 'easing'),
      );
    case 'title:':
      return materialTypography('title-size', 'title-weight', material('color', 'on-surface'));
    case 'body:':
      return materialTypography('body-size', 'body-weight', material('color', 'on-surface'));
    case 'label:':
      return materialTypography('label-size', 'label-weight', material('color', 'muted'));
    case 'divider:':
      return [decl('display', 'block'), tokenDecl('border-bottom', material('border', 'divider'))];
    case 'border:focus':
      return [tokenDecl('border', material('border', 'focus'))];
    case 'field:':
      return withTransition(
        [
          ...materialTypography('body-size', 'body-weight'),
          decl('min-height', '2.75rem'),
          tokenDecl('color', material('color', 'on-surface')),
          tokenDecl('caret-color', material('color', 'primary')),
          tokenDecl('background-color', material('color', 'field')),
          tokenDecl('background-image', material('effect', 'field-tint')),
          tokenDecl('border', material('border', 'field')),
          tokenDecl('border-radius', material('radius', 'lg')),
          tokenDecl('padding', material('space', 'field-pad')),
          tokenDecl('box-shadow', material('shadow', 'field')),
        ],
        material('effect', 'state-transition'),
        material('motion', 'duration'),
        material('motion', 'easing'),
      );
    case 'action:primary':
      return withTransition(
        [
          ...actionLayout(),
          ...materialTypography('label-size', 'label-weight'),
          tokenDecl('color', material('color', 'on-primary')),
          tokenDecl('background-color', material('color', 'primary')),
          decl('border', '0'),
          tokenDecl('border-radius', material('radius', 'pill')),
          tokenDecl('padding', material('space', 'action-pad')),
          tokenDecl('box-shadow', material('shadow', 'action')),
        ],
        material('effect', 'state-transition'),
        material('motion', 'duration'),
        material('motion', 'easing'),
      );
    case 'action:tonal':
      return withTransition(
        [
          ...actionLayout(),
          ...materialTypography('label-size', 'label-weight'),
          tokenDecl('color', material('color', 'on-primary-container')),
          tokenDecl('background-color', material('color', 'primary-container')),
          decl('border', '0'),
          tokenDecl('border-radius', material('radius', 'lg')),
          tokenDecl('padding', material('space', 'action-pad')),
          tokenDecl('box-shadow', material('shadow', 'tonal-action')),
        ],
        material('effect', 'state-transition'),
        material('motion', 'duration'),
        material('motion', 'easing'),
      );
    case 'action:outlined':
      return withTransition(
        [
          ...actionLayout(),
          ...materialTypography('label-size', 'label-weight'),
          tokenDecl('color', material('color', 'primary')),
          tokenDecl('background-color', material('color', 'surface')),
          tokenDecl('border', material('border', 'outlined-action')),
          tokenDecl('border-radius', material('radius', 'pill')),
          tokenDecl('padding', material('space', 'action-pad')),
          tokenDecl('box-shadow', material('shadow', 'outlined-action')),
        ],
        material('effect', 'state-transition'),
        material('motion', 'duration'),
        material('motion', 'easing'),
      );
    case 'elevation:1':
      return [tokenDecl('box-shadow', material('shadow', '1'))];
    case 'shadow:2':
      return [tokenDecl('box-shadow', material('shadow', '2'))];
    case 'shadow:press':
      return [tokenDecl('box-shadow', material('shadow', 'press'))];
    default:
      return null;
  }
}

function renderStylesheet(rules: RuleMatch[]): string {
  const blocks = [DEFAULT_STYLESHEET_HEADER, ...rules.map(renderRule)];
  return `${blocks.join('\n\n')}\n`;
}

function renderRule(rule: RuleMatch): string {
  let pseudoSuffix = '';
  let isDark = false;
  for (const variant of rule.variants) {
    if (variant === 'dark') {
      isDark = true;
      continue;
    }
    pseudoSuffix += `:${variant}`;
  }

  const selector = `.${escapeClassName(rule.rawClassName)}`;
  const body = rule.declarations.map((declaration) => `  ${declaration.property}: ${declaration.value};`).join('\n');
  const block = `${selector}${pseudoSuffix} {\n${body}\n}`;
  return isDark ? `@media (prefers-color-scheme: dark) {\n${indent(block, 2)}\n}` : block;
}

function escapeClassName(input: string): string {
  return input.replaceAll(':', '\\:').replaceAll('/', '\\/').replaceAll('.', '\\.') ;
}

function indent(input: string, spaces: number): string {
  const prefix = ' '.repeat(spaces);
  return input
    .split('\n')
    .map((line) => `${prefix}${line}`)
    .join('\n');
}

function decl(property: string, value: string): Declaration {
  return { property, value };
}

function tokenDecl(property: string, value: string): Declaration {
  return { property, value };
}

function actionLayout(): Declaration[] {
  return [
    decl('display', 'inline-flex'),
    decl('align-items', 'center'),
    decl('justify-content', 'center'),
    decl('min-height', '2.5rem'),
    decl('line-height', '1'),
  ];
}

function withTransition(
  declarations: Declaration[],
  property: string,
  duration: string,
  easing: string,
): Declaration[] {
  return [
    ...declarations,
    tokenDecl('transition-property', property),
    tokenDecl('transition-duration', duration),
    tokenDecl('transition-timing-function', easing),
  ];
}

function fluentTypography(sizeKey: string, weightKey: string, color?: string): Declaration[] {
  return typography(registry.fluent.typography, sizeKey, weightKey, color);
}

function materialTypography(sizeKey: string, weightKey: string, color?: string): Declaration[] {
  return typography(registry.material.typography, sizeKey, weightKey, color);
}

function typography(tokens: TokenMap, sizeKey: string, weightKey: string, color?: string): Declaration[] {
  const declarations = [
    tokenDecl('font-family', tokens['font-family']),
    tokenDecl('font-size', tokens[sizeKey]),
    tokenDecl('font-weight', tokens[weightKey]),
    tokenDecl('line-height', tokens['line-height']),
    tokenDecl('letter-spacing', tokens.tracking),
  ];
  if (color) {
    declarations.push(tokenDecl('color', color));
  }
  return declarations;
}

function fluent(group: string, key: string): string {
  return getToken(registry.fluent, group, key);
}

function material(group: string, key: string): string {
  return getToken(registry.material, group, key);
}

function getToken(source: TokenGroup, group: string, key: string): string {
  const groupValues = source[group];
  if (!groupValues || !(key in groupValues)) {
    throw new Error(`missing motif token ${group}.${key}`);
  }
  return groupValues[key]!;
}

