import test from 'node:test';
import assert from 'node:assert/strict';
import { compileSources } from './core.js';

test('compileSources renders preset rules and variants into a stylesheet', () => {
  const result = compileSources([
    {
      path: '/demo/App.tsx',
      content: `
        <main class="f-surface m-surface-container">
          <button class="hover:f-bg-hover-primary focus:f-ring dark:m-elevation-1"></button>
        </main>
      `,
    },
  ]);

  assert.match(result.stylesheet, /\/\* motif\.css: generated by motif \*\//);
  assert.match(result.stylesheet, /\.f-surface \{/);
  assert.match(result.stylesheet, /background-image:/);
  assert.match(result.stylesheet, /\.hover\\:f-bg-hover-primary:hover \{/);
  assert.match(result.stylesheet, /@media \(prefers-color-scheme: dark\)/);
  assert.match(result.stylesheet, /\.dark\\:m-elevation-1 \{/);
});

test('compileSources ignores unknown tokens and deduplicates repeated classes', () => {
  const result = compileSources([
    {
      path: '/demo/one.tsx',
      content: '<div class="f-title f-title unknown-token"></div>',
    },
    {
      path: '/demo/two.tsx',
      content: '<div class="f-title"></div>',
    },
  ]);

  const titleMatches = result.stylesheet.match(/\.f-title \{/g) ?? [];
  assert.equal(titleMatches.length, 1);
  assert.doesNotMatch(result.stylesheet, /unknown-token/);
});
