import fluentTokens from '../../../tokens/fluent.json';
import materialTokens from '../../../tokens/material.json';
import type { MotifCompileAdapter, MotifCompileResult, MotifSourceFile } from './types.js';

type Variant = 'hover' | 'focus' | 'active' | 'dark';
type Family = 'f' | 'm' | 'ui';
type TokenMap = Record<string, string>;
type TokenGroup = Record<string, TokenMap>;

type ParsedClass = {
  raw: string;
  variants: Variant[];
  family: Family;
  utility: string;
  value: string | null;
};

type Declaration = {
  property: string;
  value: string;
};

type RuleMatch = {
  rawClassName: string;
  variants: Variant[];
  declarations: Declaration[];
};

const DEFAULT_STYLESHEET_HEADER = '/* motif.css: generated by motif */';
const DEFAULT_KEYFRAMES = [
  '@keyframes motif-spin {\n  to {\n    transform: rotate(360deg);\n  }\n}',
  '@keyframes motif-shimmer {\n  0% {\n    background-position: 200% 0;\n  }\n  100% {\n    background-position: -200% 0;\n  }\n}',
];
const CLASS_BOUNDARY = /[\s"'`<>=\{\}\(\)\[\],;]/;
const CLASS_CHAR = /^[A-Za-z0-9:/_.-]+$/;

const registry = {
  fluent: fluentTokens as TokenGroup,
  material: materialTokens as TokenGroup,
};

export function createTsCoreAdapter(): MotifCompileAdapter {
  return {
    compileSources(sources) {
      return compileSources(sources);
    },
  };
}

export function compileSources(sources: MotifSourceFile[]): MotifCompileResult {
  const classNames = new Set<string>();
  for (const source of sources) {
    for (const className of extractClassNames(source.content)) {
      classNames.add(className);
    }
  }

  const rules = Array.from(classNames)
    .sort((left, right) => left.localeCompare(right))
    .map(parseClassName)
    .filter((parsed): parsed is ParsedClass => parsed !== null)
    .map(resolveRule)
    .filter((rule): rule is RuleMatch => rule !== null);

  return {
    stylesheet: renderStylesheet(rules),
  };
}

function extractClassNames(content: string): Set<string> {
  const result = new Set<string>();
  for (const candidate of content.split(CLASS_BOUNDARY)) {
    const normalized = normalizeCandidate(candidate);
    if (normalized) {
      result.add(normalized);
    }
  }
  return result;
}

function normalizeCandidate(candidate: string): string | null {
  const trimmed = candidate.replace(/^[^A-Za-z0-9:/_.-]+|[^A-Za-z0-9:/_.-]+$/g, '');
  if (!trimmed || !CLASS_CHAR.test(trimmed)) {
    return null;
  }

  const utility = trimmed.split(':').at(-1) ?? trimmed;
  if (utility.startsWith('f-') || utility.startsWith('m-') || utility.startsWith('ui-')) {
    return trimmed;
  }
  return null;
}

function parseClassName(input: string): ParsedClass | null {
  if (!input) {
    return null;
  }

  const segments = input.split(':');
  const base = segments.pop();
  if (!base) {
    return null;
  }

  const variants = segments.every(isVariant) ? (segments as Variant[]) : null;
  if (!variants) {
    return null;
  }

  const family = base.startsWith('f-')
    ? 'f'
    : base.startsWith('m-')
      ? 'm'
      : base.startsWith('ui-')
        ? 'ui'
        : null;
  if (!family) {
    return null;
  }

  const body = family === 'ui' ? base.slice(3) : base.slice(2);
  if (!body) {
    return null;
  }

  const [utility, value] = splitUtility(body);
  if (!utility) {
    return null;
  }

  return {
    raw: input,
    variants,
    family,
    utility,
    value,
  };
}

function isVariant(value: string): value is Variant {
  return value === 'hover' || value === 'focus' || value === 'active' || value === 'dark';
}

function splitUtility(body: string): [string, string | null] {
  const dash = body.indexOf('-');
  if (dash === -1) {
    return [body, null];
  }
  return [body.slice(0, dash), body.slice(dash + 1)];
}

function resolveRule(parsed: ParsedClass): RuleMatch | null {
  const declarations =
    parsed.family === 'f'
      ? resolveFluent(parsed)
      : parsed.family === 'm'
        ? resolveMaterial(parsed)
        : resolveUniversal(parsed);
  if (!declarations) {
    return null;
  }
  return {
    rawClassName: parsed.raw,
    variants: parsed.variants,
    declarations,
  };
}

function resolveUniversal(parsed: ParsedClass): Declaration[] | null {
  switch (`${parsed.utility}:${parsed.value ?? ''}`) {
    case 'control:sm':
      return control('2.25rem', '0.625rem 0.85rem', '0.875rem');
    case 'control:md':
      return control('2.75rem', '0.78rem 0.95rem', '0.95rem');
    case 'control:lg':
      return control('3.25rem', '0.95rem 1.2rem', '1rem');
    case 'pad:sm':
      return [decl('padding', '0.75rem')];
    case 'pad:md':
      return [decl('padding', '1rem')];
    case 'pad:lg':
      return [decl('padding', '1.25rem')];
    case 'radius:sm':
      return [decl('border-radius', '6px')];
    case 'radius:md':
      return [decl('border-radius', '10px')];
    case 'radius:lg':
      return [decl('border-radius', '14px')];
    case 'radius:pill':
      return [decl('border-radius', '999px')];
    case 'text:sm':
      return text('0.875rem', '1.4');
    case 'text:md':
      return text('1rem', '1.5');
    case 'text:lg':
      return text('1.125rem', '1.55');
    default:
      return null;
  }
}

function resolveFluent(parsed: ParsedClass): Declaration[] | null {
  switch (`${parsed.utility}:${parsed.value ?? ''}`) {
    case 'stack:':
      return [decl('display', 'flex'), decl('flex-direction', 'column'), tokenDecl('gap', fluent('space', 'md'))];
    case 'ring:':
      return withTransition(
        [
          tokenDecl('outline-width', fluent('outline', 'focus-width')),
          decl('outline-style', 'solid'),
          tokenDecl('outline-color', fluent('color', 'primary')),
          tokenDecl('outline-offset', fluent('space', 'focus-offset')),
        ],
        fluent('effect', 'transition'),
        fluent('motion', 'duration'),
        fluent('motion', 'easing'),
      );
    case 'bg:primary':
      return [
        tokenDecl('background-color', fluent('color', 'primary')),
        tokenDecl('color', fluent('color', 'action-foreground')),
      ];
    case 'bg:hover-primary':
      return [
        tokenDecl('background-color', fluent('color', 'hover-primary')),
        tokenDecl('color', fluent('color', 'action-foreground')),
      ];
    case 'bg:hover-subtle':
      return [tokenDecl('background-color', fluent('color', 'hover-subtle'))];
    case 'text:primary':
      return [tokenDecl('color', fluent('color', 'primary'))];
    case 'text:muted':
      return [tokenDecl('color', fluent('color', 'muted'))];
    case 'surface:':
      return withTransition(
        [
          tokenDecl('background-color', fluent('color', 'surface')),
          tokenDecl('background-image', fluent('effect', 'surface-tint')),
          decl('background-blend-mode', 'screen'),
          tokenDecl('color', fluent('color', 'text')),
          tokenDecl('border-radius', fluent('radius', 'md')),
          tokenDecl('padding', fluent('space', 'surface-pad')),
          tokenDecl('border-width', fluent('border', 'subtle-width')),
          decl('border-style', 'solid'),
          tokenDecl('border-color', fluent('color', 'border')),
          tokenDecl('box-shadow', fluent('shadow', 'surface')),
          decl('backdrop-filter', 'blur(18px) saturate(1.15)'),
        ],
        fluent('effect', 'transition'),
        fluent('motion', 'duration'),
        fluent('motion', 'easing'),
      );
    case 'surface:alt':
      return withTransition(
        [
          tokenDecl('background-color', fluent('color', 'surface-alt')),
          tokenDecl('background-image', fluent('effect', 'surface-alt-tint')),
          decl('background-blend-mode', 'screen'),
          tokenDecl('color', fluent('color', 'text')),
          tokenDecl('border-radius', fluent('radius', 'sm')),
          tokenDecl('padding', fluent('space', 'surface-pad-sm')),
          tokenDecl('border-width', fluent('border', 'subtle-width')),
          decl('border-style', 'solid'),
          tokenDecl('border-color', fluent('color', 'border-strong')),
          tokenDecl('box-shadow', fluent('shadow', 'surface-alt')),
          decl('backdrop-filter', 'blur(28px) saturate(1.25)'),
        ],
        fluent('effect', 'transition'),
        fluent('motion', 'duration'),
        fluent('motion', 'easing'),
      );
    case 'panel:':
      return withTransition(
        [
          tokenDecl('background-color', fluent('color', 'panel')),
          tokenDecl('background-image', fluent('effect', 'panel-tint')),
          decl('background-blend-mode', 'screen'),
          tokenDecl('color', fluent('color', 'text')),
          tokenDecl('border', fluent('border', 'panel')),
          tokenDecl('border-radius', fluent('radius', 'lg')),
          tokenDecl('padding', fluent('space', 'panel-pad')),
          tokenDecl('box-shadow', fluent('shadow', 'panel')),
          decl('backdrop-filter', 'blur(24px) saturate(1.2)'),
        ],
        fluent('effect', 'interactive-transition'),
        fluent('motion', 'duration'),
        fluent('motion', 'easing'),
      );
    case 'shadow:press':
      return [tokenDecl('box-shadow', fluent('shadow', 'press'))];
    case 'title:':
      return fluentTypography('title-size', 'title-weight', fluent('color', 'text'));
    case 'body:':
      return fluentTypography('body-size', 'body-weight', fluent('color', 'text'));
    case 'label:':
      return fluentTypography('label-size', 'label-weight', fluent('color', 'muted'));
    case 'border:focus':
      return [tokenDecl('border', fluent('color', 'border-focus'))];
    case 'divider:':
      return [decl('display', 'block'), tokenDecl('border-bottom', fluent('border', 'divider'))];
    case 'field:':
      return withTransition(
        [
          ...fluentTypography('body-size', 'body-weight'),
          decl('min-height', '2.75rem'),
          tokenDecl('color', fluent('color', 'text')),
          tokenDecl('caret-color', fluent('color', 'primary')),
          tokenDecl('background-color', fluent('color', 'field')),
          tokenDecl('background-image', fluent('effect', 'field-tint')),
          tokenDecl('border', fluent('border', 'field')),
          tokenDecl('border-radius', fluent('radius', 'sm')),
          tokenDecl('padding', fluent('space', 'field-pad')),
          tokenDecl('box-shadow', fluent('shadow', 'field')),
          decl('backdrop-filter', 'blur(14px) saturate(1.05)'),
        ],
        fluent('effect', 'interactive-transition'),
        fluent('motion', 'duration'),
        fluent('motion', 'easing'),
      );
    case 'checkbox:':
      return withTransition(
        [
          decl('appearance', 'none'),
          decl('display', 'inline-grid'),
          decl('place-items', 'center'),
          decl('inline-size', '1.125rem'),
          decl('block-size', '1.125rem'),
          tokenDecl('background-color', fluent('color', 'surface-alt')),
          tokenDecl('border', fluent('border', 'field')),
          tokenDecl('border-radius', fluent('radius', 'sm')),
          tokenDecl('box-shadow', fluent('shadow', 'field')),
        ],
        fluent('effect', 'interactive-transition'),
        fluent('motion', 'duration'),
        fluent('motion', 'easing'),
      );
    case 'radio:':
      return withTransition(
        [
          decl('appearance', 'none'),
          decl('display', 'inline-grid'),
          decl('place-items', 'center'),
          decl('inline-size', '1.125rem'),
          decl('block-size', '1.125rem'),
          tokenDecl('background-color', fluent('color', 'surface-alt')),
          tokenDecl('border', fluent('border', 'field')),
          decl('border-radius', '999px'),
          tokenDecl('box-shadow', fluent('shadow', 'field')),
        ],
        fluent('effect', 'interactive-transition'),
        fluent('motion', 'duration'),
        fluent('motion', 'easing'),
      );
    case 'switch:':
      return withTransition(
        [
          decl('appearance', 'none'),
          decl('display', 'inline-flex'),
          decl('align-items', 'center'),
          decl('inline-size', '2.5rem'),
          decl('block-size', '1.5rem'),
          tokenDecl('background-color', fluent('color', 'surface-alt')),
          tokenDecl('border', fluent('border', 'field')),
          decl('border-radius', '999px'),
          tokenDecl('box-shadow', fluent('shadow', 'field')),
        ],
        fluent('effect', 'interactive-transition'),
        fluent('motion', 'duration'),
        fluent('motion', 'easing'),
      );
    case 'textarea:':
      return withTransition(
        [
          ...fluentTypography('body-size', 'body-weight'),
          decl('min-height', '6.5rem'),
          decl('resize', 'vertical'),
          tokenDecl('color', fluent('color', 'text')),
          tokenDecl('caret-color', fluent('color', 'primary')),
          tokenDecl('background-color', fluent('color', 'field')),
          tokenDecl('background-image', fluent('effect', 'field-tint')),
          tokenDecl('border', fluent('border', 'field')),
          tokenDecl('border-radius', fluent('radius', 'sm')),
          tokenDecl('padding', fluent('space', 'field-pad')),
          tokenDecl('box-shadow', fluent('shadow', 'field')),
          decl('backdrop-filter', 'blur(14px) saturate(1.05)'),
        ],
        fluent('effect', 'interactive-transition'),
        fluent('motion', 'duration'),
        fluent('motion', 'easing'),
      );
    case 'select:':
      return withTransition(
        [
          ...fluentTypography('body-size', 'body-weight'),
          decl('min-height', '2.75rem'),
          decl('appearance', 'none'),
          decl('background-repeat', 'no-repeat'),
          decl('background-position', 'right 0.85rem center'),
          tokenDecl('color', fluent('color', 'text')),
          tokenDecl('background-color', fluent('color', 'field')),
          tokenDecl('background-image', fluent('effect', 'field-tint')),
          tokenDecl('border', fluent('border', 'field')),
          tokenDecl('border-radius', fluent('radius', 'sm')),
          tokenDecl('padding', fluent('space', 'field-pad')),
          tokenDecl('box-shadow', fluent('shadow', 'field')),
        ],
        fluent('effect', 'interactive-transition'),
        fluent('motion', 'duration'),
        fluent('motion', 'easing'),
      );
    case 'tab:':
      return withTransition(
        [
          ...fluentTypography('label-size', 'label-weight'),
          decl('display', 'inline-flex'),
          decl('align-items', 'center'),
          decl('justify-content', 'center'),
          decl('min-height', '2.5rem'),
          tokenDecl('color', fluent('color', 'muted')),
          decl('background-color', 'transparent'),
          tokenDecl('border-radius', fluent('radius', 'md')),
          tokenDecl('padding', fluent('space', 'action-pad')),
          tokenDecl('border', fluent('border', 'action-subtle')),
        ],
        fluent('effect', 'interactive-transition'),
        fluent('motion', 'duration'),
        fluent('motion', 'easing'),
      );
    case 'dialog:':
      return withTransition(
        [
          tokenDecl('background-color', fluent('color', 'panel')),
          tokenDecl('background-image', fluent('effect', 'panel-tint')),
          decl('background-blend-mode', 'screen'),
          tokenDecl('color', fluent('color', 'text')),
          tokenDecl('border', fluent('border', 'panel')),
          tokenDecl('border-radius', fluent('radius', 'lg')),
          tokenDecl('padding', fluent('space', 'panel-pad')),
          tokenDecl('box-shadow', fluent('shadow', 'panel')),
          decl('backdrop-filter', 'blur(24px) saturate(1.2)'),
          decl('max-width', '32rem'),
          decl('width', '100%'),
        ],
        fluent('effect', 'interactive-transition'),
        fluent('motion', 'duration'),
        fluent('motion', 'easing'),
      );
    case 'list:item':
      return withTransition(
        [
          decl('display', 'flex'),
          decl('align-items', 'center'),
          decl('justify-content', 'space-between'),
          decl('min-height', '3rem'),
          tokenDecl('color', fluent('color', 'text')),
          tokenDecl('background-color', fluent('color', 'surface-alt')),
          tokenDecl('border', fluent('border', 'action-subtle')),
          tokenDecl('border-radius', fluent('radius', 'md')),
          tokenDecl('padding', fluent('space', 'surface-pad-sm')),
        ],
        fluent('effect', 'interactive-transition'),
        fluent('motion', 'duration'),
        fluent('motion', 'easing'),
      );
    case 'menu:item':
      return withTransition(
        [
          decl('display', 'flex'),
          decl('align-items', 'center'),
          decl('justify-content', 'space-between'),
          decl('min-height', '2.5rem'),
          decl('cursor', 'pointer'),
          tokenDecl('color', fluent('color', 'text')),
          tokenDecl('background-color', fluent('color', 'surface-alt')),
          tokenDecl('border', fluent('border', 'action-subtle')),
          tokenDecl('border-radius', fluent('radius', 'md')),
          tokenDecl('padding', fluent('space', 'surface-pad-sm')),
        ],
        fluent('effect', 'interactive-transition'),
        fluent('motion', 'duration'),
        fluent('motion', 'easing'),
      );
    case 'icon:button':
      return withTransition(
        [
          decl('display', 'inline-grid'),
          decl('place-items', 'center'),
          decl('inline-size', '2.5rem'),
          decl('block-size', '2.5rem'),
          tokenDecl('color', fluent('color', 'primary')),
          tokenDecl('background-color', fluent('color', 'action-subtle')),
          tokenDecl('border', fluent('border', 'action-subtle')),
          tokenDecl('border-radius', fluent('radius', 'md')),
          tokenDecl('box-shadow', fluent('shadow', 'action-subtle')),
        ],
        fluent('effect', 'interactive-transition'),
        fluent('motion', 'duration'),
        fluent('motion', 'easing'),
      );
    case 'nav:item':
      return withTransition(
        [
          ...fluentTypography('label-size', 'label-weight'),
          decl('display', 'inline-flex'),
          decl('align-items', 'center'),
          decl('min-height', '2.5rem'),
          tokenDecl('color', fluent('color', 'muted')),
          decl('background-color', 'transparent'),
          tokenDecl('border-radius', fluent('radius', 'md')),
          tokenDecl('padding', fluent('space', 'action-pad')),
        ],
        fluent('effect', 'interactive-transition'),
        fluent('motion', 'duration'),
        fluent('motion', 'easing'),
      );
    case 'badge:':
      return [
        ...fluentTypography('label-size', 'label-weight'),
        decl('display', 'inline-flex'),
        decl('align-items', 'center'),
        decl('min-height', '1.75rem'),
        tokenDecl('color', fluent('color', 'primary')),
        tokenDecl('background-color', fluent('color', 'surface-alt')),
        tokenDecl('border', fluent('border', 'action-subtle')),
        decl('border-radius', '999px'),
        tokenDecl('padding', fluent('space', 'surface-pad-sm')),
      ];
    case 'tooltip:':
      return [
        ...fluentTypography('label-size', 'label-weight'),
        tokenDecl('color', fluent('color', 'text')),
        tokenDecl('background-color', fluent('color', 'surface-alt')),
        tokenDecl('border', fluent('border', 'action-subtle')),
        tokenDecl('border-radius', fluent('radius', 'sm')),
        tokenDecl('padding', fluent('space', 'surface-pad-sm')),
        tokenDecl('box-shadow', fluent('shadow', 'surface-alt')),
      ];
    case 'banner:':
      return withTransition(
        [
          decl('display', 'flex'),
          decl('align-items', 'center'),
          decl('justify-content', 'space-between'),
          tokenDecl('color', fluent('color', 'text')),
          tokenDecl('background-color', fluent('color', 'surface-alt')),
          tokenDecl('border', fluent('border', 'panel')),
          tokenDecl('border-radius', fluent('radius', 'md')),
          tokenDecl('padding', fluent('space', 'surface-pad-sm')),
        ],
        fluent('effect', 'interactive-transition'),
        fluent('motion', 'duration'),
        fluent('motion', 'easing'),
      );
    case 'drawer:':
      return withTransition(
        [
          decl('display', 'flex'),
          decl('flex-direction', 'column'),
          decl('min-width', '16rem'),
          tokenDecl('color', fluent('color', 'text')),
          tokenDecl('background-color', fluent('color', 'surface')),
          tokenDecl('background-image', fluent('effect', 'surface-tint')),
          tokenDecl('border', fluent('border', 'panel')),
          tokenDecl('border-radius', fluent('radius', 'lg')),
          tokenDecl('padding', fluent('space', 'panel-pad')),
          tokenDecl('box-shadow', fluent('shadow', 'panel')),
        ],
        fluent('effect', 'interactive-transition'),
        fluent('motion', 'duration'),
        fluent('motion', 'easing'),
      );
    case 'toast:':
      return withTransition(
        [
          decl('display', 'flex'),
          decl('align-items', 'center'),
          decl('justify-content', 'space-between'),
          tokenDecl('color', fluent('color', 'text')),
          tokenDecl('background-color', fluent('color', 'surface-alt')),
          tokenDecl('border', fluent('border', 'action-subtle')),
          tokenDecl('border-radius', fluent('radius', 'md')),
          tokenDecl('padding', fluent('space', 'surface-pad-sm')),
          tokenDecl('box-shadow', fluent('shadow', 'surface-alt')),
        ],
        fluent('effect', 'interactive-transition'),
        fluent('motion', 'duration'),
        fluent('motion', 'easing'),
      );
    case 'segmented:button':
      return withTransition(
        [
          ...fluentTypography('label-size', 'label-weight'),
          decl('display', 'inline-flex'),
          decl('align-items', 'center'),
          decl('justify-content', 'center'),
          decl('min-height', '2.5rem'),
          tokenDecl('color', fluent('color', 'text')),
          tokenDecl('background-color', fluent('color', 'surface-alt')),
          tokenDecl('border', fluent('border', 'action-subtle')),
          tokenDecl('border-radius', fluent('radius', 'md')),
          tokenDecl('padding', fluent('space', 'action-pad')),
        ],
        fluent('effect', 'interactive-transition'),
        fluent('motion', 'duration'),
        fluent('motion', 'easing'),
      );
    case 'search:field':
      return withTransition(
        [
          ...fluentTypography('body-size', 'body-weight'),
          decl('min-height', '2.75rem'),
          decl('padding-left', '2.5rem'),
          tokenDecl('color', fluent('color', 'text')),
          tokenDecl('caret-color', fluent('color', 'primary')),
          tokenDecl('background-color', fluent('color', 'field')),
          tokenDecl('background-image', fluent('effect', 'field-tint')),
          tokenDecl('border', fluent('border', 'field')),
          tokenDecl('border-radius', fluent('radius', 'sm')),
          tokenDecl('padding', fluent('space', 'field-pad')),
          tokenDecl('box-shadow', fluent('shadow', 'field')),
        ],
        fluent('effect', 'interactive-transition'),
        fluent('motion', 'duration'),
        fluent('motion', 'easing'),
      );
    case 'breadcrumb:':
      return withTransition(
        [
          decl('display', 'inline-flex'),
          decl('align-items', 'center'),
          decl('flex-wrap', 'wrap'),
          decl('gap', '0.5rem'),
          tokenDecl('color', fluent('color', 'muted')),
        ],
        fluent('effect', 'transition'),
        fluent('motion', 'duration'),
        fluent('motion', 'easing'),
      );
    case 'breadcrumb:item':
      return [
        ...fluentTypography('label-size', 'label-weight'),
        decl('display', 'inline-flex'),
        decl('align-items', 'center'),
        tokenDecl('color', fluent('color', 'muted')),
      ];
    case 'avatar:':
      return withTransition(
        [
          decl('display', 'inline-grid'),
          decl('place-items', 'center'),
          decl('inline-size', '2.5rem'),
          decl('block-size', '2.5rem'),
          tokenDecl('color', fluent('color', 'text')),
          tokenDecl('background-color', fluent('color', 'surface-alt')),
          decl('border-radius', '999px'),
          tokenDecl('border', fluent('border', 'action-subtle')),
        ],
        fluent('effect', 'interactive-transition'),
        fluent('motion', 'duration'),
        fluent('motion', 'easing'),
      );
    case 'persona:':
      return withTransition(
        [
          decl('display', 'flex'),
          decl('align-items', 'center'),
          decl('gap', '0.75rem'),
          tokenDecl('color', fluent('color', 'text')),
          tokenDecl('background-color', fluent('color', 'surface-alt')),
          tokenDecl('border', fluent('border', 'action-subtle')),
          tokenDecl('border-radius', fluent('radius', 'md')),
          tokenDecl('padding', fluent('space', 'surface-pad-sm')),
        ],
        fluent('effect', 'interactive-transition'),
        fluent('motion', 'duration'),
        fluent('motion', 'easing'),
      );
    case 'progress:':
      return withTransition(
        [
          decl('display', 'block'),
          decl('inline-size', '100%'),
          decl('block-size', '0.5rem'),
          tokenDecl('background-color', fluent('color', 'surface-alt')),
          decl('border-radius', '999px'),
          tokenDecl('background-image', fluent('effect', 'surface-alt-tint')),
          tokenDecl('border', fluent('border', 'action-subtle')),
        ],
        fluent('effect', 'interactive-transition'),
        fluent('motion', 'duration'),
        fluent('motion', 'easing'),
      );
    case 'spinner:':
      return withTransition(
        [
          decl('display', 'inline-block'),
          decl('inline-size', '1.25rem'),
          decl('block-size', '1.25rem'),
          decl('border-width', '2px'),
          decl('border-style', 'solid'),
          tokenDecl('border-color', fluent('color', 'border')),
          tokenDecl('border-top-color', fluent('color', 'primary')),
          decl('border-radius', '999px'),
          decl('animation', 'motif-spin 0.9s linear infinite'),
        ],
        fluent('effect', 'transition'),
        fluent('motion', 'duration'),
        fluent('motion', 'easing'),
      );
    case 'skeleton:':
      return withTransition(
        [
          decl('display', 'block'),
          decl('min-height', '1rem'),
          tokenDecl('background-color', fluent('color', 'surface-alt')),
          decl(
            'background-image',
            'linear-gradient(90deg, rgba(255, 255, 255, 0.06), rgba(255, 255, 255, 0.4), rgba(255, 255, 255, 0.08))',
          ),
          decl('background-size', '200% 100%'),
          tokenDecl('border-radius', fluent('radius', 'sm')),
          decl('animation', 'motif-shimmer 1.4s ease-in-out infinite'),
        ],
        fluent('effect', 'transition'),
        fluent('motion', 'duration'),
        fluent('motion', 'easing'),
      );
    case 'empty:state':
      return withTransition(
        [
          decl('display', 'grid'),
          decl('justify-items', 'start'),
          decl('gap', '0.75rem'),
          tokenDecl('color', fluent('color', 'muted')),
          tokenDecl('background-color', fluent('color', 'surface-alt')),
          tokenDecl('border', fluent('border', 'action-subtle')),
          tokenDecl('border-radius', fluent('radius', 'lg')),
          tokenDecl('padding', fluent('space', 'panel-pad')),
          tokenDecl('box-shadow', fluent('shadow', 'surface-alt')),
        ],
        fluent('effect', 'interactive-transition'),
        fluent('motion', 'duration'),
        fluent('motion', 'easing'),
      );
    case 'sheet:':
      return withTransition(
        [
          tokenDecl('background-color', fluent('color', 'panel')),
          tokenDecl('background-image', fluent('effect', 'panel-tint')),
          decl('background-blend-mode', 'screen'),
          tokenDecl('color', fluent('color', 'text')),
          tokenDecl('border', fluent('border', 'panel')),
          tokenDecl('border-radius', fluent('radius', 'lg')),
          tokenDecl('padding', fluent('space', 'panel-pad')),
          tokenDecl('box-shadow', fluent('shadow', 'panel')),
          decl('backdrop-filter', 'blur(24px) saturate(1.2)'),
          decl('max-width', '28rem'),
          decl('width', '100%'),
          decl('margin-inline', 'auto'),
        ],
        fluent('effect', 'interactive-transition'),
        fluent('motion', 'duration'),
        fluent('motion', 'easing'),
      );
    case 'accordion:item':
      return withTransition(
        [
          decl('display', 'grid'),
          decl('gap', '0.75rem'),
          tokenDecl('color', fluent('color', 'text')),
          tokenDecl('background-color', fluent('color', 'surface-alt')),
          tokenDecl('border', fluent('border', 'action-subtle')),
          tokenDecl('border-radius', fluent('radius', 'md')),
          tokenDecl('padding', fluent('space', 'surface-pad-sm')),
        ],
        fluent('effect', 'interactive-transition'),
        fluent('motion', 'duration'),
        fluent('motion', 'easing'),
      );
    case 'accordion:item-open':
      return withTransition(
        [
          decl('display', 'grid'),
          decl('gap', '0.75rem'),
          tokenDecl('color', fluent('color', 'text')),
          tokenDecl('background-color', fluent('color', 'surface-alt')),
          tokenDecl('background-image', fluent('effect', 'surface-alt-tint')),
          tokenDecl('border', fluent('border', 'action-subtle')),
          tokenDecl('border-radius', fluent('radius', 'md')),
          tokenDecl('padding', fluent('space', 'surface-pad-sm')),
          tokenDecl('box-shadow', fluent('shadow', 'surface-alt')),
        ],
        fluent('effect', 'interactive-transition'),
        fluent('motion', 'duration'),
        fluent('motion', 'easing'),
      );
    case 'table:row':
      return withTransition(
        [
          decl('display', 'grid'),
          decl('grid-template-columns', 'minmax(0, 2fr) minmax(0, 1fr) auto'),
          decl('align-items', 'center'),
          decl('gap', '0.75rem'),
          decl('min-height', '3rem'),
          tokenDecl('color', fluent('color', 'text')),
          tokenDecl('background-color', fluent('color', 'surface-alt')),
          tokenDecl('border', fluent('border', 'action-subtle')),
          tokenDecl('border-radius', fluent('radius', 'sm')),
          tokenDecl('padding', fluent('space', 'surface-pad-sm')),
        ],
        fluent('effect', 'interactive-transition'),
        fluent('motion', 'duration'),
        fluent('motion', 'easing'),
      );
    case 'table:row-selected':
      return withTransition(
        [
          decl('display', 'grid'),
          decl('grid-template-columns', 'minmax(0, 2fr) minmax(0, 1fr) auto'),
          decl('align-items', 'center'),
          decl('gap', '0.75rem'),
          decl('min-height', '3rem'),
          tokenDecl('color', fluent('color', 'text')),
          tokenDecl('background-color', fluent('color', 'surface-alt')),
          tokenDecl('background-image', fluent('effect', 'surface-alt-tint')),
          tokenDecl('border', fluent('border', 'action-subtle')),
          tokenDecl('border-color', fluent('color', 'border-strong')),
          tokenDecl('border-radius', fluent('radius', 'sm')),
          tokenDecl('padding', fluent('space', 'surface-pad-sm')),
        ],
        fluent('effect', 'interactive-transition'),
        fluent('motion', 'duration'),
        fluent('motion', 'easing'),
      );
    case 'action:primary':
      return withTransition(
        [
          ...actionLayout(),
          ...fluentTypography('label-size', 'label-weight'),
          tokenDecl('color', fluent('color', 'action-foreground')),
          tokenDecl('background-color', fluent('color', 'primary')),
          tokenDecl('border', fluent('border', 'action-primary')),
          tokenDecl('border-radius', fluent('radius', 'md')),
          tokenDecl('padding', fluent('space', 'action-pad')),
          tokenDecl('box-shadow', fluent('shadow', 'action')),
        ],
        fluent('effect', 'interactive-transition'),
        fluent('motion', 'duration'),
        fluent('motion', 'easing'),
      );
    case 'action:subtle':
      return withTransition(
        [
          ...actionLayout(),
          ...fluentTypography('label-size', 'label-weight'),
          tokenDecl('color', fluent('color', 'primary')),
          tokenDecl('background-color', fluent('color', 'action-subtle')),
          tokenDecl('border', fluent('border', 'action-subtle')),
          tokenDecl('border-radius', fluent('radius', 'md')),
          tokenDecl('padding', fluent('space', 'action-pad')),
          tokenDecl('box-shadow', fluent('shadow', 'action-subtle')),
          decl('backdrop-filter', 'blur(18px) saturate(1.08)'),
        ],
        fluent('effect', 'interactive-transition'),
        fluent('motion', 'duration'),
        fluent('motion', 'easing'),
      );
    default:
      return null;
  }
}

function resolveMaterial(parsed: ParsedClass): Declaration[] | null {
  switch (`${parsed.utility}:${parsed.value ?? ''}`) {
    case 'surface:':
      return withTransition(
        [
          tokenDecl('background-color', material('color', 'surface')),
          tokenDecl('background-image', material('effect', 'surface-tint')),
          tokenDecl('color', material('color', 'on-surface')),
          tokenDecl('border-radius', material('radius', 'lg')),
          decl('padding', '1.25rem'),
          tokenDecl('box-shadow', material('shadow', 'surface')),
        ],
        material('effect', 'transition'),
        material('motion', 'duration'),
        material('motion', 'easing'),
      );
    case 'surface:container':
      return withTransition(
        [
          tokenDecl('background-color', material('color', 'surface-container')),
          tokenDecl('background-image', material('effect', 'container-tint')),
          tokenDecl('color', material('color', 'on-surface')),
          tokenDecl('border', material('border', 'surface-container')),
          tokenDecl('border-radius', material('radius', 'lg')),
          decl('padding', '1rem'),
          tokenDecl('box-shadow', material('shadow', 'container-high')),
        ],
        material('effect', 'state-transition'),
        material('motion', 'duration'),
        material('motion', 'easing'),
      );
    case 'surface:variant':
      return withTransition(
        [
          tokenDecl('background-color', material('color', 'surface-variant')),
          tokenDecl('background-image', material('effect', 'variant-tint')),
          tokenDecl('color', material('color', 'on-surface')),
          tokenDecl('border-radius', material('radius', 'lg')),
          decl('padding', '1rem'),
          tokenDecl('box-shadow', material('shadow', 'container')),
        ],
        material('effect', 'transition'),
        material('motion', 'duration'),
        material('motion', 'easing'),
      );
    case 'bg:primary':
      return withTransition(
        [
          tokenDecl('background-color', material('color', 'primary')),
          tokenDecl('color', material('color', 'on-primary')),
          tokenDecl('border-radius', material('radius', 'pill')),
        ],
        material('effect', 'state-transition'),
        material('motion', 'duration'),
        material('motion', 'easing'),
      );
    case 'bg:hover-primary':
      return [tokenDecl('background-color', material('color', 'hover-primary'))];
    case 'bg:hover-container':
      return [tokenDecl('background-color', material('color', 'hover-container'))];
    case 'bg:hover-surface':
      return [tokenDecl('background-color', material('color', 'hover-surface'))];
    case 'bg:primary-container':
      return withTransition(
        [
          tokenDecl('background-color', material('color', 'primary-container')),
          tokenDecl('color', material('color', 'on-primary-container')),
          tokenDecl('border-radius', material('radius', 'lg')),
          tokenDecl('box-shadow', material('shadow', 'container')),
        ],
        material('effect', 'state-transition'),
        material('motion', 'duration'),
        material('motion', 'easing'),
      );
    case 'text:primary':
      return [tokenDecl('color', material('color', 'primary'))];
    case 'text:on-primary':
      return [tokenDecl('color', material('color', 'on-primary'))];
    case 'text:muted':
      return [tokenDecl('color', material('color', 'muted'))];
    case 'ring:':
      return withTransition(
        [
          decl('outline-width', '2px'),
          decl('outline-style', 'solid'),
          tokenDecl('outline-color', material('color', 'primary')),
          decl('outline-offset', '2px'),
          decl('box-shadow', '0 0 0 4px rgba(26, 115, 232, 0.16)'),
        ],
        material('effect', 'state-transition'),
        material('motion', 'duration'),
        material('motion', 'easing'),
      );
    case 'title:':
      return materialTypography('title-size', 'title-weight', material('color', 'on-surface'));
    case 'body:':
      return materialTypography('body-size', 'body-weight', material('color', 'on-surface'));
    case 'label:':
      return materialTypography('label-size', 'label-weight', material('color', 'muted'));
    case 'divider:':
      return [decl('display', 'block'), tokenDecl('border-bottom', material('border', 'divider'))];
    case 'border:focus':
      return [tokenDecl('border', material('border', 'focus'))];
    case 'field:':
      return withTransition(
        [
          ...materialTypography('body-size', 'body-weight'),
          decl('min-height', '2.75rem'),
          tokenDecl('color', material('color', 'on-surface')),
          tokenDecl('caret-color', material('color', 'primary')),
          tokenDecl('background-color', material('color', 'field')),
          tokenDecl('background-image', material('effect', 'field-tint')),
          tokenDecl('border', material('border', 'field')),
          tokenDecl('border-radius', material('radius', 'lg')),
          tokenDecl('padding', material('space', 'field-pad')),
          tokenDecl('box-shadow', material('shadow', 'field')),
        ],
        material('effect', 'state-transition'),
        material('motion', 'duration'),
        material('motion', 'easing'),
      );
    case 'checkbox:':
      return withTransition(
        [
          decl('appearance', 'none'),
          decl('display', 'inline-grid'),
          decl('place-items', 'center'),
          decl('inline-size', '1.125rem'),
          decl('block-size', '1.125rem'),
          tokenDecl('background-color', material('color', 'surface')),
          tokenDecl('border', material('border', 'outlined-action')),
          tokenDecl('border-radius', material('radius', 'md')),
          tokenDecl('box-shadow', material('shadow', 'outlined-action')),
        ],
        material('effect', 'state-transition'),
        material('motion', 'duration'),
        material('motion', 'easing'),
      );
    case 'radio:':
      return withTransition(
        [
          decl('appearance', 'none'),
          decl('display', 'inline-grid'),
          decl('place-items', 'center'),
          decl('inline-size', '1.125rem'),
          decl('block-size', '1.125rem'),
          tokenDecl('background-color', material('color', 'surface')),
          tokenDecl('border', material('border', 'outlined-action')),
          tokenDecl('border-radius', material('radius', 'pill')),
          tokenDecl('box-shadow', material('shadow', 'outlined-action')),
        ],
        material('effect', 'state-transition'),
        material('motion', 'duration'),
        material('motion', 'easing'),
      );
    case 'switch:':
      return withTransition(
        [
          decl('appearance', 'none'),
          decl('display', 'inline-flex'),
          decl('align-items', 'center'),
          decl('inline-size', '2.5rem'),
          decl('block-size', '1.5rem'),
          tokenDecl('background-color', material('color', 'surface-container')),
          tokenDecl('border', material('border', 'outlined-action')),
          tokenDecl('border-radius', material('radius', 'pill')),
          tokenDecl('box-shadow', material('shadow', 'outlined-action')),
        ],
        material('effect', 'state-transition'),
        material('motion', 'duration'),
        material('motion', 'easing'),
      );
    case 'textarea:':
      return withTransition(
        [
          ...materialTypography('body-size', 'body-weight'),
          decl('min-height', '6.5rem'),
          decl('resize', 'vertical'),
          tokenDecl('color', material('color', 'on-surface')),
          tokenDecl('caret-color', material('color', 'primary')),
          tokenDecl('background-color', material('color', 'field')),
          tokenDecl('background-image', material('effect', 'field-tint')),
          tokenDecl('border', material('border', 'field')),
          tokenDecl('border-radius', material('radius', 'lg')),
          tokenDecl('padding', material('space', 'field-pad')),
          tokenDecl('box-shadow', material('shadow', 'field')),
        ],
        material('effect', 'state-transition'),
        material('motion', 'duration'),
        material('motion', 'easing'),
      );
    case 'select:':
      return withTransition(
        [
          ...materialTypography('body-size', 'body-weight'),
          decl('min-height', '2.75rem'),
          decl('appearance', 'none'),
          decl('background-repeat', 'no-repeat'),
          decl('background-position', 'right 0.85rem center'),
          tokenDecl('color', material('color', 'on-surface')),
          tokenDecl('background-color', material('color', 'field')),
          tokenDecl('background-image', material('effect', 'field-tint')),
          tokenDecl('border', material('border', 'field')),
          tokenDecl('border-radius', material('radius', 'lg')),
          tokenDecl('padding', material('space', 'field-pad')),
          tokenDecl('box-shadow', material('shadow', 'field')),
        ],
        material('effect', 'state-transition'),
        material('motion', 'duration'),
        material('motion', 'easing'),
      );
    case 'tab:':
      return withTransition(
        [
          ...materialTypography('label-size', 'label-weight'),
          decl('display', 'inline-flex'),
          decl('align-items', 'center'),
          decl('justify-content', 'center'),
          decl('min-height', '2.5rem'),
          tokenDecl('color', material('color', 'primary')),
          decl('background-color', 'transparent'),
          tokenDecl('border-radius', material('radius', 'pill')),
          tokenDecl('padding', material('space', 'action-pad')),
          tokenDecl('border', material('border', 'outlined-action')),
        ],
        material('effect', 'state-transition'),
        material('motion', 'duration'),
        material('motion', 'easing'),
      );
    case 'dialog:':
      return withTransition(
        [
          tokenDecl('background-color', material('color', 'surface-container')),
          tokenDecl('background-image', material('effect', 'container-tint')),
          tokenDecl('color', material('color', 'on-surface')),
          tokenDecl('border', material('border', 'surface-container')),
          tokenDecl('border-radius', material('radius', 'lg')),
          decl('padding', '1rem'),
          tokenDecl('box-shadow', material('shadow', 'container-high')),
          decl('max-width', '32rem'),
          decl('width', '100%'),
        ],
        material('effect', 'state-transition'),
        material('motion', 'duration'),
        material('motion', 'easing'),
      );
    case 'list:item':
      return withTransition(
        [
          decl('display', 'flex'),
          decl('align-items', 'center'),
          decl('justify-content', 'space-between'),
          decl('min-height', '3rem'),
          tokenDecl('color', material('color', 'on-surface')),
          tokenDecl('background-color', material('color', 'surface-container')),
          tokenDecl('border', material('border', 'surface-container')),
          tokenDecl('border-radius', material('radius', 'lg')),
          decl('padding', '0.85rem 1rem'),
        ],
        material('effect', 'state-transition'),
        material('motion', 'duration'),
        material('motion', 'easing'),
      );
    case 'menu:item':
      return withTransition(
        [
          decl('display', 'flex'),
          decl('align-items', 'center'),
          decl('justify-content', 'space-between'),
          decl('min-height', '2.5rem'),
          decl('cursor', 'pointer'),
          tokenDecl('color', material('color', 'on-surface')),
          tokenDecl('background-color', material('color', 'surface-container')),
          tokenDecl('border', material('border', 'surface-container')),
          tokenDecl('border-radius', material('radius', 'lg')),
          decl('padding', '0.85rem 1rem'),
        ],
        material('effect', 'state-transition'),
        material('motion', 'duration'),
        material('motion', 'easing'),
      );
    case 'icon:button':
      return withTransition(
        [
          decl('display', 'inline-grid'),
          decl('place-items', 'center'),
          decl('inline-size', '2.5rem'),
          decl('block-size', '2.5rem'),
          tokenDecl('color', material('color', 'primary')),
          tokenDecl('background-color', material('color', 'surface-container')),
          tokenDecl('border', material('border', 'outlined-action')),
          tokenDecl('border-radius', material('radius', 'pill')),
          tokenDecl('box-shadow', material('shadow', 'outlined-action')),
        ],
        material('effect', 'state-transition'),
        material('motion', 'duration'),
        material('motion', 'easing'),
      );
    case 'nav:item':
      return withTransition(
        [
          ...materialTypography('label-size', 'label-weight'),
          decl('display', 'inline-flex'),
          decl('align-items', 'center'),
          decl('min-height', '2.5rem'),
          tokenDecl('color', material('color', 'primary')),
          decl('background-color', 'transparent'),
          tokenDecl('border-radius', material('radius', 'pill')),
          tokenDecl('padding', material('space', 'action-pad')),
        ],
        material('effect', 'state-transition'),
        material('motion', 'duration'),
        material('motion', 'easing'),
      );
    case 'badge:':
      return [
        ...materialTypography('label-size', 'label-weight'),
        decl('display', 'inline-flex'),
        decl('align-items', 'center'),
        decl('min-height', '1.75rem'),
        tokenDecl('color', material('color', 'on-primary-container')),
        tokenDecl('background-color', material('color', 'primary-container')),
        decl('border', '0'),
        tokenDecl('border-radius', material('radius', 'pill')),
        decl('padding', '0.35rem 0.75rem'),
      ];
    case 'tooltip:':
      return [
        ...materialTypography('label-size', 'label-weight'),
        tokenDecl('color', material('color', 'on-surface')),
        tokenDecl('background-color', material('color', 'surface-container')),
        tokenDecl('border', material('border', 'surface-container')),
        tokenDecl('border-radius', material('radius', 'lg')),
        decl('padding', '0.5rem 0.75rem'),
        tokenDecl('box-shadow', material('shadow', 'container')),
      ];
    case 'banner:':
      return withTransition(
        [
          decl('display', 'flex'),
          decl('align-items', 'center'),
          decl('justify-content', 'space-between'),
          tokenDecl('color', material('color', 'on-surface')),
          tokenDecl('background-color', material('color', 'surface-container')),
          tokenDecl('border', material('border', 'surface-container')),
          tokenDecl('border-radius', material('radius', 'lg')),
          decl('padding', '0.85rem 1rem'),
        ],
        material('effect', 'state-transition'),
        material('motion', 'duration'),
        material('motion', 'easing'),
      );
    case 'drawer:':
      return withTransition(
        [
          decl('display', 'flex'),
          decl('flex-direction', 'column'),
          decl('min-width', '16rem'),
          tokenDecl('color', material('color', 'on-surface')),
          tokenDecl('background-color', material('color', 'surface-container')),
          tokenDecl('background-image', material('effect', 'container-tint')),
          tokenDecl('border', material('border', 'surface-container')),
          tokenDecl('border-radius', material('radius', 'lg')),
          decl('padding', '1rem'),
          tokenDecl('box-shadow', material('shadow', 'container-high')),
        ],
        material('effect', 'state-transition'),
        material('motion', 'duration'),
        material('motion', 'easing'),
      );
    case 'toast:':
      return withTransition(
        [
          decl('display', 'flex'),
          decl('align-items', 'center'),
          decl('justify-content', 'space-between'),
          tokenDecl('color', material('color', 'on-surface')),
          tokenDecl('background-color', material('color', 'surface-container')),
          tokenDecl('border', material('border', 'surface-container')),
          tokenDecl('border-radius', material('radius', 'lg')),
          decl('padding', '0.85rem 1rem'),
          tokenDecl('box-shadow', material('shadow', 'container')),
        ],
        material('effect', 'state-transition'),
        material('motion', 'duration'),
        material('motion', 'easing'),
      );
    case 'segmented:button':
      return withTransition(
        [
          ...materialTypography('label-size', 'label-weight'),
          decl('display', 'inline-flex'),
          decl('align-items', 'center'),
          decl('justify-content', 'center'),
          decl('min-height', '2.5rem'),
          tokenDecl('color', material('color', 'primary')),
          tokenDecl('background-color', material('color', 'surface-container')),
          tokenDecl('border', material('border', 'outlined-action')),
          tokenDecl('border-radius', material('radius', 'pill')),
          tokenDecl('padding', material('space', 'action-pad')),
        ],
        material('effect', 'state-transition'),
        material('motion', 'duration'),
        material('motion', 'easing'),
      );
    case 'search:field':
      return withTransition(
        [
          ...materialTypography('body-size', 'body-weight'),
          decl('min-height', '2.75rem'),
          decl('padding-left', '2.5rem'),
          tokenDecl('color', material('color', 'on-surface')),
          tokenDecl('caret-color', material('color', 'primary')),
          tokenDecl('background-color', material('color', 'field')),
          tokenDecl('background-image', material('effect', 'field-tint')),
          tokenDecl('border', material('border', 'field')),
          tokenDecl('border-radius', material('radius', 'lg')),
          tokenDecl('padding', material('space', 'field-pad')),
          tokenDecl('box-shadow', material('shadow', 'field')),
        ],
        material('effect', 'state-transition'),
        material('motion', 'duration'),
        material('motion', 'easing'),
      );
    case 'breadcrumb:':
      return withTransition(
        [
          decl('display', 'inline-flex'),
          decl('align-items', 'center'),
          decl('flex-wrap', 'wrap'),
          decl('gap', '0.5rem'),
          tokenDecl('color', material('color', 'muted')),
        ],
        material('effect', 'transition'),
        material('motion', 'duration'),
        material('motion', 'easing'),
      );
    case 'breadcrumb:item':
      return [
        ...materialTypography('label-size', 'label-weight'),
        decl('display', 'inline-flex'),
        decl('align-items', 'center'),
        tokenDecl('color', material('color', 'muted')),
      ];
    case 'avatar:':
      return withTransition(
        [
          decl('display', 'inline-grid'),
          decl('place-items', 'center'),
          decl('inline-size', '2.5rem'),
          decl('block-size', '2.5rem'),
          tokenDecl('color', material('color', 'on-primary-container')),
          tokenDecl('background-color', material('color', 'primary-container')),
          tokenDecl('border-radius', material('radius', 'pill')),
          decl('border', '0'),
        ],
        material('effect', 'state-transition'),
        material('motion', 'duration'),
        material('motion', 'easing'),
      );
    case 'persona:':
      return withTransition(
        [
          decl('display', 'flex'),
          decl('align-items', 'center'),
          decl('gap', '0.75rem'),
          tokenDecl('color', material('color', 'on-surface')),
          tokenDecl('background-color', material('color', 'surface-container')),
          tokenDecl('border', material('border', 'surface-container')),
          tokenDecl('border-radius', material('radius', 'lg')),
          decl('padding', '0.85rem 1rem'),
        ],
        material('effect', 'state-transition'),
        material('motion', 'duration'),
        material('motion', 'easing'),
      );
    case 'progress:':
      return withTransition(
        [
          decl('display', 'block'),
          decl('inline-size', '100%'),
          decl('block-size', '0.5rem'),
          tokenDecl('background-color', material('color', 'surface-container')),
          tokenDecl('border-radius', material('radius', 'pill')),
          tokenDecl('background-image', material('effect', 'container-tint')),
          tokenDecl('border', material('border', 'surface-container')),
        ],
        material('effect', 'state-transition'),
        material('motion', 'duration'),
        material('motion', 'easing'),
      );
    case 'spinner:':
      return withTransition(
        [
          decl('display', 'inline-block'),
          decl('inline-size', '1.25rem'),
          decl('block-size', '1.25rem'),
          decl('border-width', '2px'),
          decl('border-style', 'solid'),
          tokenDecl('border-color', material('color', 'surface-variant')),
          tokenDecl('border-top-color', material('color', 'primary')),
          tokenDecl('border-radius', material('radius', 'pill')),
          decl('animation', 'motif-spin 0.9s linear infinite'),
        ],
        material('effect', 'state-transition'),
        material('motion', 'duration'),
        material('motion', 'easing'),
      );
    case 'skeleton:':
      return withTransition(
        [
          decl('display', 'block'),
          decl('min-height', '1rem'),
          tokenDecl('background-color', material('color', 'surface-container')),
          decl(
            'background-image',
            'linear-gradient(90deg, rgba(255, 255, 255, 0.12), rgba(255, 255, 255, 0.56), rgba(211, 227, 253, 0.2))',
          ),
          decl('background-size', '200% 100%'),
          tokenDecl('border-radius', material('radius', 'lg')),
          decl('animation', 'motif-shimmer 1.4s ease-in-out infinite'),
        ],
        material('effect', 'transition'),
        material('motion', 'duration'),
        material('motion', 'easing'),
      );
    case 'empty:state':
      return withTransition(
        [
          decl('display', 'grid'),
          decl('justify-items', 'start'),
          decl('gap', '0.75rem'),
          tokenDecl('color', material('color', 'muted')),
          tokenDecl('background-color', material('color', 'surface-container')),
          tokenDecl('border', material('border', 'surface-container')),
          tokenDecl('border-radius', material('radius', 'lg')),
          decl('padding', '1rem'),
          tokenDecl('box-shadow', material('shadow', 'container')),
        ],
        material('effect', 'state-transition'),
        material('motion', 'duration'),
        material('motion', 'easing'),
      );
    case 'sheet:':
      return withTransition(
        [
          tokenDecl('background-color', material('color', 'surface-container')),
          tokenDecl('background-image', material('effect', 'container-tint')),
          tokenDecl('color', material('color', 'on-surface')),
          tokenDecl('border', material('border', 'surface-container')),
          tokenDecl('border-radius', material('radius', 'lg')),
          decl('padding', '1rem'),
          tokenDecl('box-shadow', material('shadow', 'container-high')),
          decl('max-width', '28rem'),
          decl('width', '100%'),
          decl('margin-inline', 'auto'),
        ],
        material('effect', 'state-transition'),
        material('motion', 'duration'),
        material('motion', 'easing'),
      );
    case 'accordion:item':
      return withTransition(
        [
          decl('display', 'grid'),
          decl('gap', '0.75rem'),
          tokenDecl('color', material('color', 'on-surface')),
          tokenDecl('background-color', material('color', 'surface-container')),
          tokenDecl('border', material('border', 'surface-container')),
          tokenDecl('border-radius', material('radius', 'lg')),
          decl('padding', '1rem'),
        ],
        material('effect', 'state-transition'),
        material('motion', 'duration'),
        material('motion', 'easing'),
      );
    case 'accordion:item-open':
      return withTransition(
        [
          decl('display', 'grid'),
          decl('gap', '0.75rem'),
          tokenDecl('color', material('color', 'on-surface')),
          tokenDecl('background-color', material('color', 'surface-container')),
          tokenDecl('background-image', material('effect', 'container-tint')),
          tokenDecl('border', material('border', 'surface-container')),
          tokenDecl('border-radius', material('radius', 'lg')),
          decl('padding', '1rem'),
          tokenDecl('box-shadow', material('shadow', 'container')),
        ],
        material('effect', 'state-transition'),
        material('motion', 'duration'),
        material('motion', 'easing'),
      );
    case 'table:row':
      return withTransition(
        [
          decl('display', 'grid'),
          decl('grid-template-columns', 'minmax(0, 2fr) minmax(0, 1fr) auto'),
          decl('align-items', 'center'),
          decl('gap', '0.75rem'),
          decl('min-height', '3rem'),
          tokenDecl('color', material('color', 'on-surface')),
          tokenDecl('background-color', material('color', 'surface-container')),
          tokenDecl('border', material('border', 'surface-container')),
          tokenDecl('border-radius', material('radius', 'md')),
          decl('padding', '0.85rem 1rem'),
        ],
        material('effect', 'state-transition'),
        material('motion', 'duration'),
        material('motion', 'easing'),
      );
    case 'table:row-selected':
      return withTransition(
        [
          decl('display', 'grid'),
          decl('grid-template-columns', 'minmax(0, 2fr) minmax(0, 1fr) auto'),
          decl('align-items', 'center'),
          decl('gap', '0.75rem'),
          decl('min-height', '3rem'),
          tokenDecl('color', material('color', 'on-surface')),
          tokenDecl('background-color', material('color', 'surface-container')),
          tokenDecl('background-image', material('effect', 'container-tint')),
          tokenDecl('border', material('border', 'surface-container')),
          tokenDecl('border-color', material('color', 'primary')),
          tokenDecl('border-radius', material('radius', 'md')),
          decl('padding', '0.85rem 1rem'),
        ],
        material('effect', 'state-transition'),
        material('motion', 'duration'),
        material('motion', 'easing'),
      );
    case 'action:primary':
      return withTransition(
        [
          ...actionLayout(),
          ...materialTypography('label-size', 'label-weight'),
          tokenDecl('color', material('color', 'on-primary')),
          tokenDecl('background-color', material('color', 'primary')),
          decl('border', '0'),
          tokenDecl('border-radius', material('radius', 'pill')),
          tokenDecl('padding', material('space', 'action-pad')),
          tokenDecl('box-shadow', material('shadow', 'action')),
        ],
        material('effect', 'state-transition'),
        material('motion', 'duration'),
        material('motion', 'easing'),
      );
    case 'action:tonal':
      return withTransition(
        [
          ...actionLayout(),
          ...materialTypography('label-size', 'label-weight'),
          tokenDecl('color', material('color', 'on-primary-container')),
          tokenDecl('background-color', material('color', 'primary-container')),
          decl('border', '0'),
          tokenDecl('border-radius', material('radius', 'lg')),
          tokenDecl('padding', material('space', 'action-pad')),
          tokenDecl('box-shadow', material('shadow', 'tonal-action')),
        ],
        material('effect', 'state-transition'),
        material('motion', 'duration'),
        material('motion', 'easing'),
      );
    case 'action:outlined':
      return withTransition(
        [
          ...actionLayout(),
          ...materialTypography('label-size', 'label-weight'),
          tokenDecl('color', material('color', 'primary')),
          tokenDecl('background-color', material('color', 'surface')),
          tokenDecl('border', material('border', 'outlined-action')),
          tokenDecl('border-radius', material('radius', 'pill')),
          tokenDecl('padding', material('space', 'action-pad')),
          tokenDecl('box-shadow', material('shadow', 'outlined-action')),
        ],
        material('effect', 'state-transition'),
        material('motion', 'duration'),
        material('motion', 'easing'),
      );
    case 'elevation:1':
      return [tokenDecl('box-shadow', material('shadow', '1'))];
    case 'shadow:2':
      return [tokenDecl('box-shadow', material('shadow', '2'))];
    case 'shadow:press':
      return [tokenDecl('box-shadow', material('shadow', 'press'))];
    default:
      return null;
  }
}

function renderStylesheet(rules: RuleMatch[]): string {
  const blocks = [DEFAULT_STYLESHEET_HEADER, ...DEFAULT_KEYFRAMES, ...rules.map(renderRule)];
  return `${blocks.join('\n\n')}\n`;
}

function renderRule(rule: RuleMatch): string {
  let pseudoSuffix = '';
  let isDark = false;
  for (const variant of rule.variants) {
    if (variant === 'dark') {
      isDark = true;
      continue;
    }
    pseudoSuffix += `:${variant}`;
  }

  const selector = `.${escapeClassName(rule.rawClassName)}`;
  const body = rule.declarations.map((declaration) => `  ${declaration.property}: ${declaration.value};`).join('\n');
  const block = `${selector}${pseudoSuffix} {\n${body}\n}`;
  return isDark ? `@media (prefers-color-scheme: dark) {\n${indent(block, 2)}\n}` : block;
}

function escapeClassName(input: string): string {
  return input.replaceAll(':', '\\:').replaceAll('/', '\\/').replaceAll('.', '\\.') ;
}

function indent(input: string, spaces: number): string {
  const prefix = ' '.repeat(spaces);
  return input
    .split('\n')
    .map((line) => `${prefix}${line}`)
    .join('\n');
}

function decl(property: string, value: string): Declaration {
  return { property, value };
}

function tokenDecl(property: string, value: string): Declaration {
  return { property, value };
}

function actionLayout(): Declaration[] {
  return [
    decl('display', 'inline-flex'),
    decl('align-items', 'center'),
    decl('justify-content', 'center'),
    decl('min-height', '2.5rem'),
    decl('line-height', '1'),
  ];
}

function control(minHeight: string, padding: string, fontSize: string): Declaration[] {
  return [
    decl('min-height', minHeight),
    decl('padding', padding),
    decl('font-size', fontSize),
  ];
}

function text(fontSize: string, lineHeight: string): Declaration[] {
  return [decl('font-size', fontSize), decl('line-height', lineHeight)];
}

function withTransition(
  declarations: Declaration[],
  property: string,
  duration: string,
  easing: string,
): Declaration[] {
  return [
    ...declarations,
    tokenDecl('transition-property', property),
    tokenDecl('transition-duration', duration),
    tokenDecl('transition-timing-function', easing),
  ];
}

function fluentTypography(sizeKey: string, weightKey: string, color?: string): Declaration[] {
  return typography(registry.fluent.typography, sizeKey, weightKey, color);
}

function materialTypography(sizeKey: string, weightKey: string, color?: string): Declaration[] {
  return typography(registry.material.typography, sizeKey, weightKey, color);
}

function typography(tokens: TokenMap, sizeKey: string, weightKey: string, color?: string): Declaration[] {
  const declarations = [
    tokenDecl('font-family', tokens['font-family']),
    tokenDecl('font-size', tokens[sizeKey]),
    tokenDecl('font-weight', tokens[weightKey]),
    tokenDecl('line-height', tokens['line-height']),
    tokenDecl('letter-spacing', tokens.tracking),
  ];
  if (color) {
    declarations.push(tokenDecl('color', color));
  }
  return declarations;
}

function fluent(group: string, key: string): string {
  return getToken(registry.fluent, group, key);
}

function material(group: string, key: string): string {
  return getToken(registry.material, group, key);
}

function getToken(source: TokenGroup, group: string, key: string): string {
  const groupValues = source[group];
  if (!groupValues || !(key in groupValues)) {
    throw new Error(`missing motif token ${group}.${key}`);
  }
  return groupValues[key]!;
}

