import type { RuleMatch } from './types.js';

const DEFAULT_STYLESHEET_HEADER = '/* motif.css: generated by motif */';
const DEFAULT_KEYFRAMES = [
  '@keyframes motif-spin {\n  to {\n    transform: rotate(360deg);\n  }\n}',
  '@keyframes motif-shimmer {\n  0% {\n    background-position: 200% 0;\n  }\n  100% {\n    background-position: -200% 0;\n  }\n}',
];

export function renderStylesheet(rules: RuleMatch[]): string {
  const blocks = [DEFAULT_STYLESHEET_HEADER, ...DEFAULT_KEYFRAMES, ...rules.map(renderRule)];
  return `${blocks.join('\n\n')}\n`;
}

function renderRule(rule: RuleMatch): string {
  let pseudoSuffix = '';
  let isDark = false;
  for (const variant of rule.variants) {
    if (variant === 'dark') {
      isDark = true;
      continue;
    }
    pseudoSuffix += `:${variant}`;
  }

  const selector = `.${escapeClassName(rule.rawClassName)}`;
  const body = rule.declarations
    .map((declaration) => `  ${declaration.property}: ${declaration.value};`)
    .join('\n');
  const block = `${selector}${pseudoSuffix} {\n${body}\n}`;
  return isDark ? `@media (prefers-color-scheme: dark) {\n${indent(block, 2)}\n}` : block;
}

function escapeClassName(input: string): string {
  return input.replaceAll(':', '\\:').replaceAll('/', '\\/').replaceAll('.', '\\.');
}

function indent(input: string, spaces: number): string {
  const prefix = ' '.repeat(spaces);
  return input
    .split('\n')
    .map((line) => `${prefix}${line}`)
    .join('\n');
}
